import { type ReactNode, Children, isValidElement, useId } from 'react';
import type { RadioProps } from '../../Radio';
import type { RadioGroupProps } from '../types';

export const useRadioGroupName = (
    groupName: string | undefined,
    children?: ReactNode,
    options?: RadioGroupProps['options'],
): string | undefined => {
    const generatedName = useId();

    if (groupName) return groupName;

    let names: (string | undefined)[] = [];
    if (options && options.length > 0) {
        names = options.map((item) => item.name);
    } else if (children) {
        Children.forEach(children, (child) => {
            if (!isValidElement(child)) return;
            const props = child.props as RadioProps;
            if (props.name) names.push(props.name);
        });
    }

    const hasAnyName = names.some(Boolean);
    if (!hasAnyName) return undefined;

    const firstName = names.find(Boolean);
    const allNamesEqual = names.every((item) => item === firstName);

    if (allNamesEqual && firstName) return firstName;

    console.warn(
        '[RadioGroup]: options/children have inconsistent `name` values, falling back to autogenerated one.',
    );

    return generatedName;
};
